---
title: "Something fascinating"
author: "Saurabh Mishra"
date: "`r format(Sys.Date())`"
output: github_document
---

Pre-Requisite libraries:
1. gapminder
2. tidyverse

Working with the Gapminder dataset

```{r setup, cache = FALSE, message = FALSE, warning = FALSE}

library(gapminder)
library(tidyverse)

# Get an overview of the gapminder dataset
str(gapminder)

# Type of objects in gapminder
class(gapminder)

gapminder

# Initial rows of dataset
head(gapminder)

# Last rows of dataset
tail(gapminder)

# Column names in dataset
names(gapminder)

# Number of rows
nrow(gapminder)

# Number of columns
ncol(gapminder)

# Number of rows x columns
dim(gapminder)

# statistical overview
summary(gapminder)

# visualizing dataset
plot(lifeExp ~ year, gapminder)

plot(lifeExp ~ gdpPercap, gapminder)

plot(lifeExp ~ log(gdpPercap), gapminder)
```

Variables of Data Frame

```{r cache = FALSE, message = FALSE, warning = FALSE}
library(gapminder)
library(tidyverse)

head(gapminder$lifeExp)

summary(gapminder$lifeExp)

hist(gapminder$lifeExp)
```



```{r cache = FALSE, message = FALSE, warning = FALSE}
library(gapminder)
library(tidyverse)

## we exploit the fact that ggplot2 was installed and loaded via the tidyverse
p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp)) # just initializes
p <- p + scale_x_log10() # log the x axis the right way
p + geom_point() # scatterplot
p + geom_point(aes(color = continent)) # map continent to color
p + geom_point(alpha = (1/3), size = 3) + geom_smooth(lwd = 3, se = FALSE)
p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)
```

